### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by eschwalm** [eschwalm/readfeeder#9]

**Comment by debsfong** [comment]
Two strange things happening with your auth
- [x] I can sign up with a password of any length, or no password at all for that matter
- [x] Hitting enter on my keyboard doesn't submit the form?? This is very strange.

**Comment by debsfong** [comment]
This looks great! The last thing I would ask before I mark this complete is for errors to display with some space inbetween, or one above another. Currently, when you sign up with 2 errors, they display with no space between them.

**Comment by eschwalm** [comment]
@debsfong This should be fixed now, thanks!

**Comment by debsfong** [comment]
Looks great!
